# Generated by Django 2.1.5 on 2020-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('item_category', models.CharField(max_length=255)),
            ],
        ),
    ]
