# Generated by Django 2.1.5 on 2020-04-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200424_1500'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=5),
        ),
    ]
