# Generated by Django 2.1.5 on 2020-04-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200424_1513'),
    ]

    operations = [
        
    ]
