# Generated by Django 2.1.5 on 2020-04-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200424_1546'),
    ]

    operations = [
        
    ]
