# Generated by Django 2.1.5 on 2020-04-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200424_1548'),
    ]

    operations = [
        
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
        
    ]
