# Generated by Django 2.1.5 on 2020-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200427_1401'),
        ('orders', '0006_auto_20200427_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ManyToManyField(to='orders.Order')),
                ('product', models.ManyToManyField(to='menu.Product')),
            ],
        ),
    ]
