# Generated by Django 2.1.5 on 2020-04-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200427_1401'),
        ('orders', '0008_remove_orderitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, to='menu.Product'),
        ),
    ]
