# Generated by Django 2.1.5 on 2020-04-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitems_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
