# Generated by Django 2.1.5 on 2020-04-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200428_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
