# Generated by Django 2.1.5 on 2020-04-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopping_cart',
            field=models.ManyToManyField(default=0, to='orders.ShoppingCart'),
        ),
    ]
