# Generated by Django 2.1.5 on 2020-04-29 12:55

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200429_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
