# Generated by Django 2.1.5 on 2020-04-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200429_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='items',
        ),
    ]
