# Generated by Django 2.1.5 on 2020-04-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200429_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sum',
            new_name='total',
        ),
    ]
